"""Safety profile data model and formatting.

Defines the structured 9-section safety profile that is the final
output of the Phase 3 RAG pipeline.
"""

import json
import logging
from dataclasses import dataclass, field
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


@dataclass
class SafetyProfile:
    """Comprehensive toxicological safety profile for a molecule.

    Generated by the RAG pipeline from retrieved documents + LLM synthesis.
    Contains 9 structured sections plus metadata.
    """

    # Molecule identification
    iupac_name: str
    common_name: str = ""
    cas_number: str = ""
    smiles: str = ""
    inchikey: str = ""

    # Phase 1 outputs
    toxicity_score: float = 0.0
    severity_label: str = ""
    is_toxic: bool = False

    # Phase 2 CoT summary
    cot_mechanism: str = ""
    cot_functional_groups: List[str] = field(default_factory=list)

    # Phase 3 RAG: 9 safety profile sections + confidence rationale
    toxicity_mechanism: str = ""
    affected_organs: str = ""
    symptoms_of_exposure: str = ""
    dose_response: str = ""
    first_aid: str = ""
    handling_precautions: str = ""
    regulatory_classification: str = ""
    related_compounds: str = ""
    references: str = ""
    confidence_rationale: str = ""

    # Metadata
    num_retrieved_docs: int = 0
    retrieval_sources: List[str] = field(default_factory=list)
    llm_model: str = ""
    llm_latency_ms: float = 0.0

    def summary(self) -> str:
        """One-line summary of the safety profile."""
        name = self.common_name or self.iupac_name
        toxic_str = "TOXIC" if self.is_toxic else "Non-toxic"
        sections_filled = sum(1 for s in self._get_sections().values() if s)
        return (
            f"{name}: {toxic_str} (P={self.toxicity_score:.3f}) | "
            f"{sections_filled}/9 sections | "
            f"{self.num_retrieved_docs} sources"
        )

    def _get_sections(self) -> Dict[str, str]:
        """Get all 9 safety profile sections as a dict."""
        return {
            "Toxicity Mechanism": self.toxicity_mechanism,
            "Affected Organs & Systems": self.affected_organs,
            "Symptoms of Exposure": self.symptoms_of_exposure,
            "Dose-Response Data": self.dose_response,
            "First Aid & Emergency Procedures": self.first_aid,
            "Handling & Storage Precautions": self.handling_precautions,
            "Regulatory Classification": self.regulatory_classification,
            "Structurally Related Toxic Compounds": self.related_compounds,
            "References": self.references,
            "Confidence Rationale": self.confidence_rationale,
        }

    def detailed_report(self) -> str:
        """Full multi-line safety profile report for display / export."""
        name = self.common_name or self.iupac_name
        separator = "=" * 72
        thin_sep = "-" * 72
        lines = [
            separator,
            f"  TOXICOLOGICAL SAFETY PROFILE: {name}",
            separator,
            "",
        ]

        # Identification
        lines.append("  IDENTIFICATION")
        lines.append(thin_sep)
        if self.iupac_name:
            lines.append(f"  IUPAC Name:    {self.iupac_name}")
        if self.common_name:
            lines.append(f"  Common Name:   {self.common_name}")
        if self.cas_number:
            lines.append(f"  CAS Number:    {self.cas_number}")
        if self.smiles:
            lines.append(f"  SMILES:        {self.smiles}")
        if self.inchikey:
            lines.append(f"  InChIKey:      {self.inchikey}")
        lines.append("")

        # Phase 1 + 2 summary
        lines.append("  TOXGUARD ANALYSIS (Phase 1 + 2)")
        lines.append(thin_sep)
        lines.append(f"  Toxicity Score:  P(toxic) = {self.toxicity_score:.3f}")
        lines.append(f"  Severity:        {self.severity_label}")
        lines.append(f"  Classification:  {'TOXIC' if self.is_toxic else 'NON-TOXIC'}")
        if self.cot_functional_groups:
            groups = ", ".join(self.cot_functional_groups[:5])
            lines.append(f"  Functional Groups: {groups}")
        if self.cot_mechanism:
            lines.append(f"  CoT Mechanism: {self.cot_mechanism[:150]}...")
        lines.append("")

        # 9 safety sections
        lines.append("  COMPREHENSIVE SAFETY PROFILE (Phase 3 RAG)")
        lines.append(separator)

        for i, (title, content) in enumerate(self._get_sections().items(), 1):
            lines.append("")
            lines.append(f"  {i}. {title.upper()}")
            lines.append(thin_sep)
            if content:
                for line in content.split("\n"):
                    lines.append(f"    {line}")
            else:
                lines.append("    [Data not available]")

        # Footer
        lines.append("")
        lines.append(separator)
        sources = ", ".join(set(self.retrieval_sources)) if self.retrieval_sources else "None"
        lines.append(f"  Sources: {sources} | Documents: {self.num_retrieved_docs}")
        lines.append(f"  LLM: {self.llm_model} | Latency: {self.llm_latency_ms:.0f}ms")
        lines.append(separator)

        return "\n".join(lines)

    def to_dict(self) -> dict:
        """Serialize to JSON-compatible dictionary."""
        return {
            "iupac_name": self.iupac_name,
            "common_name": self.common_name,
            "cas_number": self.cas_number,
            "smiles": self.smiles,
            "inchikey": self.inchikey,
            "toxicity_score": self.toxicity_score,
            "severity_label": self.severity_label,
            "is_toxic": self.is_toxic,
            "cot_mechanism": self.cot_mechanism,
            "cot_functional_groups": self.cot_functional_groups,
            "toxicity_mechanism": self.toxicity_mechanism,
            "affected_organs": self.affected_organs,
            "symptoms_of_exposure": self.symptoms_of_exposure,
            "dose_response": self.dose_response,
            "first_aid": self.first_aid,
            "handling_precautions": self.handling_precautions,
            "regulatory_classification": self.regulatory_classification,
            "related_compounds": self.related_compounds,
            "references": self.references,
            "confidence_rationale": self.confidence_rationale,
            "num_retrieved_docs": self.num_retrieved_docs,
            "retrieval_sources": self.retrieval_sources,
            "llm_model": self.llm_model,
            "llm_latency_ms": self.llm_latency_ms,
        }

    def to_json(self, indent: int = 2) -> str:
        """Serialize to JSON string."""
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_dict(cls, data: dict) -> "SafetyProfile":
        """Deserialize from dictionary."""
        return cls(**{
            k: v for k, v in data.items()
            if k in cls.__dataclass_fields__
        })
