"""Phase 4 → Phase 2/3 Handoff: Before/After Toxicological Dossier.

After Phase 4 finds a detoxified candidate, this module pipes both the
seed (original toxic) and candidate (proposed safer) molecules through:
    - Phase 2 (CoT): Chain-of-Thought mechanistic reasoning
    - Phase 3 (RAG): Retrieval-augmented safety profile generation

The result is a side-by-side toxicological dossier showing exactly
what changed and why the candidate is safer.

Usage:
    from detox_dossier import DossierGenerator

    gen = DossierGenerator(groq_api_key="gsk_...")
    dossier = gen.generate_dossier(detox_report)
    print(dossier.format_report())
"""

import logging
import os
import sys
import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

# ── Path setup ─────────────────────────────────────────────────────────
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PHASE1_DIR = os.path.join(PROJECT_ROOT, "Phase1-IUPACGPT")
PHASE2_DIR = os.path.join(PROJECT_ROOT, "Phase2-CoT")
PHASE3_DIR = os.path.join(PROJECT_ROOT, "Phase3-RAG")
CHECKPOINT_DIR = os.path.join(PROJECT_ROOT, "iupacGPT", "iupac-gpt", "checkpoints", "iupac")
SPM_PATH = os.path.join(PROJECT_ROOT, "iupacGPT", "iupac-gpt", "iupac_gpt", "iupac_spm.model")
CHROMA_DIR = os.path.join(PHASE3_DIR, "chroma_db")


@dataclass
class MoleculeDossier:
    """Toxicological profile for a single molecule (seed or candidate)."""
    iupac_name: str
    smiles: str = ""
    p_toxic: float = 0.0
    severity: str = ""

    # Phase 2 CoT outputs
    cot_structural_analysis: str = ""
    cot_mechanism: str = ""
    cot_biological_pathways: str = ""
    cot_organ_toxicity: str = ""
    cot_functional_groups: List[str] = field(default_factory=list)
    cot_confidence: str = ""
    cot_verdict: str = ""

    # Phase 3 RAG outputs
    rag_toxicity_mechanism: str = ""
    rag_affected_organs: str = ""
    rag_symptoms: str = ""
    rag_dose_response: str = ""
    rag_first_aid: str = ""
    rag_handling: str = ""
    rag_regulatory: str = ""
    rag_related_compounds: str = ""
    rag_references: str = ""
    rag_sections_filled: int = 0
    rag_total_sections: int = 0
    rag_num_docs: int = 0


@dataclass
class DetoxDossier:
    """Complete before/after toxicological dossier."""
    seed: Optional[MoleculeDossier] = None
    candidate: Optional[MoleculeDossier] = None

    # Detox summary
    delta_toxicity: float = 0.0
    tanimoto: float = 0.0
    qed: float = 0.0
    rounds_used: int = 0
    total_time_s: float = 0.0

    # LLM-generated comparative analysis (Phase 2/3 handoff)
    comparative_analysis: str = ""

    def format_report(self) -> str:
        """Format the before/after dossier as a readable report."""
        W = 78
        border = "═" * W
        sep = "─" * W

        lines = [
            "",
            f"  {border}",
            f"  ║{'TOXICOLOGICAL DOSSIER: BEFORE vs AFTER':^{W-4}}║",
            f"  {border}",
            "",
        ]

        if self.seed and self.candidate:
            lines.extend([
                f"  {sep}",
                f"   DETOXIFICATION SUMMARY",
                f"  {sep}",
                f"      Seed molecule:      {self.seed.iupac_name}",
                f"      Proposed candidate: {self.candidate.iupac_name}",
                f"      P(toxic):           {self.seed.p_toxic:.3f} → {self.candidate.p_toxic:.3f} "
                f"(Δ = {self.delta_toxicity:+.3f})",
                f"      Tanimoto:           {self.tanimoto:.3f}",
                f"      QED:                {self.qed:.3f}",
                f"      Rounds:             {self.rounds_used}",
                "",
            ])

        # ── Seed molecule profile ─────────────────────────
        if self.seed:
            lines.extend(self._format_molecule_section(
                self.seed, "ORIGINAL MOLECULE (TOXIC)", "A"
            ))

        # ── Candidate molecule profile ────────────────────
        if self.candidate:
            lines.extend(self._format_molecule_section(
                self.candidate, "PROPOSED CANDIDATE (DETOXIFIED)", "B"
            ))

        # ── Comparative analysis ──────────────────────────
        if self.seed and self.candidate:
            lines.extend(self._format_comparison())

        lines.extend([
            f"  {border}",
            f"      Generated by ToxGuard Phase 4 → 2/3 Handoff",
            f"      This dossier does not replace professional toxicological assessment.",
            f"  {border}",
            "",
        ])

        return "\n".join(lines)

    def _format_molecule_section(
        self, mol: MoleculeDossier, title: str, label: str
    ) -> List[str]:
        """Format a single molecule's full profile."""
        W = 78
        sep = "─" * W

        lines = [
            "",
            f"  {sep}",
            f"   [{label}] {title}",
            f"  {sep}",
            f"      IUPAC:     {mol.iupac_name}",
            f"      SMILES:    {mol.smiles or 'N/A'}",
            f"      P(toxic):  {mol.p_toxic:.3f}",
            f"      Severity:  {mol.severity}",
            "",
        ]

        # Phase 2: CoT Analysis
        if mol.cot_mechanism or mol.cot_structural_analysis:
            lines.append(f"      ── Chain-of-Thought Analysis (Phase 2) ──")
            lines.append("")

            if mol.cot_functional_groups:
                groups = ", ".join(mol.cot_functional_groups[:8])
                lines.append(f"      Functional Groups: {groups}")
                lines.append("")

            cot_sections = [
                ("Structural Analysis", mol.cot_structural_analysis),
                ("Mechanism of Action", mol.cot_mechanism),
                ("Biological Pathways", mol.cot_biological_pathways),
                ("Organ Toxicity", mol.cot_organ_toxicity),
                ("Confidence", mol.cot_confidence),
                ("Verdict", mol.cot_verdict),
            ]
            for title, content in cot_sections:
                if content:
                    lines.append(f"      {title}:")
                    for line in content.strip().split("\n")[:6]:
                        lines.append(f"        {line.strip()}")
                    lines.append("")

        # Phase 3: RAG Safety Profile
        rag_sections = [
            ("Toxicity Mechanism", mol.rag_toxicity_mechanism),
            ("Affected Organs", mol.rag_affected_organs),
            ("Symptoms of Exposure", mol.rag_symptoms),
            ("Dose-Response", mol.rag_dose_response),
            ("First Aid", mol.rag_first_aid),
            ("Handling & Storage", mol.rag_handling),
            ("Regulatory Classification", mol.rag_regulatory),
            ("Related Compounds", mol.rag_related_compounds),
        ]

        has_rag = any(content for _, content in rag_sections)
        if has_rag:
            lines.append(f"      ── RAG Safety Profile (Phase 3) ──")
            lines.append(f"      ({mol.rag_sections_filled}/{mol.rag_total_sections} "
                         f"sections, {mol.rag_num_docs} docs retrieved)")
            lines.append("")
            for title, content in rag_sections:
                if content:
                    lines.append(f"      {title}:")
                    for line in content.strip().split("\n")[:4]:
                        lines.append(f"        {line.strip()}")
                    lines.append("")

        return lines

    # SMARTS lookup for verifying LLM-reported group removal
    _GROUP_SMARTS = {
        "benzene": "c1ccccc1", "phenyl": "c1ccccc1",
        "aromatic ring": "c1ccccc1", "naphthalene": "c1ccc2ccccc2c1",
        "hydroxyl": "[OX2H]", "carboxyl": "[CX3](=O)[OX2H1]",
        "carboxylic acid": "[CX3](=O)[OX2H1]",
        "amino": "[NX3;H2,H1;!$(NC=O)]", "amine": "[NX3;H2,H1;!$(NC=O)]",
        "nitro": "[NX3+](=O)[O-]", "sulfonic acid": "[SX4](=O)(=O)[OX2H]",
        "aldehyde": "[CX3H1](=O)", "ketone": "[CX3](=O)[#6]",
        "ether": "[OD2]([#6])[#6]", "ester": "[CX3](=O)[OX2][#6]",
        "amide": "[CX3](=O)[NX3]", "halide": "[F,Cl,Br,I]",
        "methyl": "[CH3]", "methoxy": "[OX2][CH3]",
        "cyano": "[CX2]#[NX1]", "nitrile": "[CX2]#[NX1]",
        "thiol": "[SX2H]", "sulfide": "[#16X2]",
    }

    @staticmethod
    def _has_substructure(smiles: str, smarts: str) -> bool:
        try:
            from rdkit import Chem
            mol = Chem.MolFromSmiles(smiles)
            pat = Chem.MolFromSmarts(smarts)
            return mol is not None and pat is not None and mol.HasSubstructMatch(pat)
        except Exception:
            return False

    def _format_comparison(self) -> List[str]:
        """Format comparative analysis including LLM-generated reasoning."""
        W = 78
        sep = "─" * W

        lines = [
            "",
            f"  {sep}",
            f"   [C] COMPARATIVE DETOXIFICATION ANALYSIS",
            f"  {sep}",
            "",
        ]

        # Toxicity comparison summary
        if self.seed.p_toxic > self.candidate.p_toxic:
            reduction_pct = ((self.seed.p_toxic - self.candidate.p_toxic)
                             / self.seed.p_toxic * 100)
            lines.append(
                f"      ✓ Toxicity reduced by {reduction_pct:.1f}% "
                f"({self.seed.p_toxic:.3f} → {self.candidate.p_toxic:.3f})"
            )
        else:
            lines.append(
                f"      ⚠ Candidate is NOT less toxic "
                f"({self.seed.p_toxic:.3f} → {self.candidate.p_toxic:.3f})"
            )

        # Functional group diff with RDKit verification
        seed_groups = set(self.seed.cot_functional_groups)
        cand_groups = set(self.candidate.cot_functional_groups)
        raw_added = cand_groups - seed_groups
        raw_removed = seed_groups - cand_groups

        # Filter out false removals:
        #   1. Group still present in candidate SMILES (false removal)
        #   2. Group was never in seed SMILES (LLM hallucination)
        removed = set()
        for g in raw_removed:
            smarts = self._GROUP_SMARTS.get(g.lower().strip())
            if smarts:
                # Verify group was actually in seed (not hallucinated)
                if self.seed.smiles and not self._has_substructure(self.seed.smiles, smarts):
                    continue  # LLM hallucinated this group for the seed
                # Verify group is actually absent from candidate
                if self.candidate.smiles and self._has_substructure(self.candidate.smiles, smarts):
                    continue  # still present → not actually removed
            removed.add(g)

        # Filter out false additions:
        #   1. Group already present in seed SMILES (not new)
        #   2. Group not actually in candidate SMILES (LLM hallucination)
        added = set()
        for g in raw_added:
            smarts = self._GROUP_SMARTS.get(g.lower().strip())
            if smarts:
                # Verify group actually exists in candidate
                if self.candidate.smiles and not self._has_substructure(self.candidate.smiles, smarts):
                    continue  # LLM hallucinated this group for the candidate
                # Verify group is actually new (not in seed)
                if self.seed.smiles and self._has_substructure(self.seed.smiles, smarts):
                    continue  # already present in seed
            added.add(g)

        if added:
            lines.append(f"      [+] Groups added:   {', '.join(sorted(added))}")
        if removed:
            lines.append(f"      [-] Groups removed:  {', '.join(sorted(removed))}")
        if not added and not removed:
            lines.append(f"      [=] Same functional group profile")
        lines.append("")

        # LLM-generated comparative reasoning
        if self.comparative_analysis:
            lines.append(f"      ── Pharmacological Rationale (LLM-Generated) ──")
            lines.append("")
            for line in self.comparative_analysis.strip().split("\n"):
                lines.append(f"        {line.strip()}")
            lines.append("")
        else:
            # Fallback: basic mechanism comparison
            if (self.seed.cot_mechanism and self.candidate.cot_mechanism
                    and self.seed.cot_mechanism != self.candidate.cot_mechanism):
                lines.append(f"      Mechanism shift:")
                seed_mech = self.seed.cot_mechanism.strip().split("\n")[0][:70]
                cand_mech = self.candidate.cot_mechanism.strip().split("\n")[0][:70]
                lines.append(f"        Before: {seed_mech}")
                lines.append(f"        After:  {cand_mech}")
                lines.append("")

        return lines


class DossierGenerator:
    """Generates before/after toxicological dossiers via Phase 2/3 handoff.

    Requires a Groq API key for LLM-powered CoT reasoning and RAG generation.

    Args:
        groq_api_key: Groq API key.
        groq_model: LLM model name.
        predictor: Optional Phase 1 ToxGuardPredictor.
        vector_store_dir: Path to ChromaDB for Phase 3 RAG.
    """

    def __init__(
        self,
        groq_api_key: str,
        groq_model: str = "llama-3.3-70b-versatile",
        predictor=None,
        vector_store_dir: Optional[str] = None,
    ):
        self.groq_api_key = groq_api_key
        self.groq_model = groq_model
        self.predictor = predictor
        self.vector_store_dir = vector_store_dir or CHROMA_DIR

        self._cot_analyzer = None
        self._rag_pipeline = None
        self._llm_client = None

    def _get_llm_client(self):
        """Get or create the Groq LLM client for comparative analysis."""
        if self._llm_client is not None:
            return self._llm_client

        if PHASE2_DIR not in sys.path:
            sys.path.append(PHASE2_DIR)

        from llm_client import GroqLLMClient
        self._llm_client = GroqLLMClient(
            api_key=self.groq_api_key, model=self.groq_model
        )
        return self._llm_client

    def _ensure_phase2(self):
        """Lazy-load Phase 2 CoT analyzer."""
        if self._cot_analyzer is not None:
            return

        if PHASE2_DIR not in sys.path:
            sys.path.append(PHASE2_DIR)

        from llm_client import GroqLLMClient
        from cot_analyzer import CoTAnalyzer

        llm = GroqLLMClient(api_key=self.groq_api_key, model=self.groq_model)
        self._cot_analyzer = CoTAnalyzer(llm_client=llm)
        logger.info("Phase 2 CoT analyzer loaded for dossier generation")

    def _ensure_phase3(self):
        """Lazy-load Phase 3 RAG pipeline."""
        if self._rag_pipeline is not None:
            return

        import importlib.util

        rag_path = os.path.join(PHASE3_DIR, "rag_pipeline.py")
        spec = importlib.util.spec_from_file_location(
            "phase3_rag_pipeline", rag_path,
            submodule_search_locations=[PHASE3_DIR],
        )
        mod = importlib.util.module_from_spec(spec)
        sys.path.insert(0, PHASE3_DIR)
        try:
            spec.loader.exec_module(mod)
        finally:
            if PHASE3_DIR in sys.path:
                sys.path.remove(PHASE3_DIR)

        self._rag_pipeline = mod.RAGPipeline(
            vector_store_dir=self.vector_store_dir,
            groq_api_key=self.groq_api_key,
            groq_model=self.groq_model,
            predictor=self.predictor,
            cot_analyzer=None,  # We run CoT separately for more control
            enable_pubchem=True,
        )
        logger.info("Phase 3 RAG pipeline loaded for dossier generation")

    def _analyze_molecule(
        self,
        iupac_name: str,
        smiles: str = "",
        p_toxic: float = 0.5,
        severity: str = "Unknown",
    ) -> MoleculeDossier:
        """Run Phase 2 + Phase 3 on a single molecule."""
        dossier = MoleculeDossier(
            iupac_name=iupac_name,
            smiles=smiles,
            p_toxic=p_toxic,
            severity=severity,
        )

        is_toxic = p_toxic >= 0.5

        # ── Phase 2: CoT Reasoning ────────────────────────────────
        self._ensure_phase2()
        try:
            logger.info(f"[Dossier] Phase 2 CoT for: {iupac_name}")
            cot_result = self._cot_analyzer.analyze_from_prediction(
                iupac_name=iupac_name,
                toxicity_score=p_toxic,
                severity_label=severity,
                is_toxic=is_toxic,
            )
            dossier.cot_structural_analysis = cot_result.structural_analysis
            dossier.cot_mechanism = cot_result.mechanism_of_action
            dossier.cot_biological_pathways = cot_result.biological_pathways
            dossier.cot_organ_toxicity = cot_result.organ_toxicity
            dossier.cot_functional_groups = cot_result.functional_groups
            dossier.cot_confidence = cot_result.confidence
            dossier.cot_verdict = cot_result.verdict
            logger.info(f"[Dossier] Phase 2 done: {len(cot_result.functional_groups)} groups")
        except Exception as e:
            logger.warning(f"[Dossier] Phase 2 CoT failed for {iupac_name}: {e}")

        # ── Phase 3: RAG Safety Profile ───────────────────────────
        self._ensure_phase3()
        try:
            logger.info(f"[Dossier] Phase 3 RAG for: {iupac_name}")
            profile = self._rag_pipeline.generate_safety_profile(
                iupac_name=iupac_name,
                smiles=smiles,
                toxicity_score=p_toxic,
                severity_label=severity,
                is_toxic=is_toxic,
                functional_groups=dossier.cot_functional_groups,
                cot_mechanism=dossier.cot_mechanism,
                cot_pathways=dossier.cot_biological_pathways,
            )
            dossier.rag_toxicity_mechanism = getattr(profile, "toxicity_mechanism", "")
            dossier.rag_affected_organs = getattr(profile, "affected_organs", "")
            dossier.rag_symptoms = getattr(profile, "symptoms_of_exposure", "")
            dossier.rag_dose_response = getattr(profile, "dose_response", "")
            dossier.rag_first_aid = getattr(profile, "first_aid", "")
            dossier.rag_handling = getattr(profile, "handling_precautions", "")
            dossier.rag_regulatory = getattr(profile, "regulatory_classification", "")
            dossier.rag_related_compounds = getattr(profile, "related_compounds", "")
            dossier.rag_references = getattr(profile, "references", "")
            dossier.rag_num_docs = getattr(profile, "num_retrieved_docs", 0)

            sections = profile._get_sections() if hasattr(profile, "_get_sections") else {}
            dossier.rag_total_sections = len(sections)
            dossier.rag_sections_filled = sum(1 for v in sections.values() if v)

            logger.info(
                f"[Dossier] Phase 3 done: "
                f"{dossier.rag_sections_filled}/{dossier.rag_total_sections} sections"
            )
        except Exception as e:
            logger.warning(f"[Dossier] Phase 3 RAG failed for {iupac_name}: {e}")

        return dossier

    def generate_dossier(self, detox_report, delay: float = 2.0) -> DetoxDossier:
        """Generate a complete before/after dossier from a DetoxReport.

        Args:
            detox_report: A DetoxReport from Phase 4 detox_agent.
            delay: Seconds to wait between API calls (rate limiting).

        Returns:
            DetoxDossier with seed and candidate profiles.
        """
        t0 = time.time()
        dossier = DetoxDossier()

        if not detox_report.success or detox_report.best_candidate is None:
            logger.warning("DetoxReport has no successful candidate — generating seed-only dossier")

        bc = detox_report.best_candidate

        # ── Analyze seed molecule ─────────────────────────────────
        logger.info(f"[Dossier] Analyzing seed: {detox_report.seed_iupac}")
        dossier.seed = self._analyze_molecule(
            iupac_name=detox_report.seed_iupac,
            smiles=detox_report.seed_smiles,
            p_toxic=detox_report.seed_p_toxic,
            severity=detox_report.seed_severity,
        )

        # Rate limit between API calls
        time.sleep(delay)

        # ── Analyze candidate molecule ────────────────────────────
        if bc is not None:
            # Determine severity for candidate
            cand_severity = "Unknown"
            if bc.p_toxic < 0.2:
                cand_severity = "Non-toxic"
            elif bc.p_toxic < 0.5:
                cand_severity = "Mildly toxic"
            elif bc.p_toxic < 0.65:
                cand_severity = "Moderately toxic"
            elif bc.p_toxic < 0.8:
                cand_severity = "Toxic"
            else:
                cand_severity = "Highly toxic"

            logger.info(f"[Dossier] Analyzing candidate: {bc.iupac_name}")
            dossier.candidate = self._analyze_molecule(
                iupac_name=bc.iupac_name,
                smiles=bc.smiles,
                p_toxic=bc.p_toxic,
                severity=cand_severity,
            )

            dossier.delta_toxicity = bc.p_toxic - detox_report.seed_p_toxic
            dossier.tanimoto = bc.tanimoto
            dossier.qed = bc.qed
            dossier.rounds_used = detox_report.rounds_used

            # Rate limit before comparative analysis
            time.sleep(delay)

            # ── Comparative CoT: explain WHY candidate is safer ───
            dossier.comparative_analysis = self._generate_comparative_cot(
                dossier.seed, dossier.candidate, dossier
            )

        dossier.total_time_s = time.time() - t0
        logger.info(f"[Dossier] Complete in {dossier.total_time_s:.1f}s")

        return dossier

    def _generate_comparative_cot(
        self,
        seed: MoleculeDossier,
        candidate: MoleculeDossier,
        dossier: DetoxDossier,
    ) -> str:
        """Generate LLM-powered comparative analysis between seed and candidate.

        This is the key Phase 4→2/3 handoff: it takes the individual CoT
        analyses and asks the LLM to explain the structural and
        pharmacological reasons why the candidate is safer.
        """
        try:
            llm = self._get_llm_client()

            system_prompt = (
                "You are an expert medicinal chemist and toxicologist. "
                "You are given two molecules: an original toxic molecule (SEED) "
                "and a proposed detoxified variant (CANDIDATE) generated by an "
                "AI detoxification pipeline. Your task is to provide a detailed "
                "pharmacological and structural comparison explaining exactly "
                "WHY the candidate is expected to be less toxic than the seed. "
                "Be specific about functional group changes, physicochemical "
                "property shifts, metabolic pathway alterations, and their "
                "impact on toxicity mechanisms. Use proper chemical terminology."
            )

            seed_groups = ", ".join(seed.cot_functional_groups) if seed.cot_functional_groups else "none identified"
            cand_groups = ", ".join(candidate.cot_functional_groups) if candidate.cot_functional_groups else "none identified"

            user_prompt = f"""## SEED MOLECULE (Original — Toxic)
- IUPAC: {seed.iupac_name}
- SMILES: {seed.smiles}
- P(toxic): {seed.p_toxic:.3f} ({seed.severity})
- Functional Groups: {seed_groups}
- Mechanism of Toxicity: {seed.cot_mechanism[:500] if seed.cot_mechanism else 'Unknown'}
- Organ Toxicity: {seed.cot_organ_toxicity[:300] if seed.cot_organ_toxicity else 'Unknown'}

## CANDIDATE MOLECULE (Proposed — Detoxified)
- IUPAC: {candidate.iupac_name}
- SMILES: {candidate.smiles}
- P(toxic): {candidate.p_toxic:.3f} ({candidate.severity})
- Functional Groups: {cand_groups}
- Mechanism: {candidate.cot_mechanism[:500] if candidate.cot_mechanism else 'Unknown'}
- Organ Toxicity: {candidate.cot_organ_toxicity[:300] if candidate.cot_organ_toxicity else 'Unknown'}

## STRUCTURAL RELATIONSHIP
- Tanimoto Similarity: {dossier.tanimoto:.3f}
- Toxicity Change: {seed.p_toxic:.3f} → {candidate.p_toxic:.3f} (Δ = {dossier.delta_toxicity:+.3f})

## YOUR ANALYSIS
Provide a structured comparison covering:
1. **Structural Modifications**: What specific functional groups were added/removed/modified?
2. **Physicochemical Impact**: How do these changes affect LogP, polarity, solubility, membrane permeability?
3. **Metabolic Pathway Changes**: How does the modification alter metabolic activation or detoxification pathways?
4. **Toxicity Mechanism Disruption**: Which specific toxic mechanisms from the seed are mitigated or eliminated?
5. **Residual Risks**: Are there any remaining toxicity concerns with the candidate?
6. **Overall Assessment**: Is this a pharmacologically sound detoxification? Rate confidence (HIGH/MEDIUM/LOW).

Be concise but scientifically rigorous. Maximum 400 words."""

            logger.info("[Dossier] Running comparative CoT analysis...")
            response = llm.generate(
                system_prompt=system_prompt,
                user_prompt=user_prompt,
                temperature=0.3,
                max_tokens=1500,
            )

            analysis = response.content.strip()
            logger.info(f"[Dossier] Comparative analysis generated ({len(analysis)} chars)")
            return analysis

        except Exception as e:
            logger.warning(f"[Dossier] Comparative CoT failed: {e}")
            return ""
